### ISSUE TITLE
Dockerize project to make development easier

### ISSUE THREAD

**Issue by VictorSNA** [locaweb/heartcheck-webservice#19]
Motivation
It's need to make easier to contribute to `heartcheck-webservice`!

Dockerizing it is a good start, it'll give a consistent and isolated environment.

**DOD**

- Must use the most possible updated Ruby version;
- Must pass all tests;
- README must be updated to include the recently updates.

**Comment by m8051** [comment]
@VictorSNA May I?

**Comment by VictorSNA** [comment]
Yes! Thanks @m8051 for your help! :)

**Comment by m8051** [comment]
@VictorSNA Any chance you could have a look at the PR above ^^ ... thanks
