### ISSUE TITLE
Add Simplecov to monitor the test coverage

### ISSUE THREAD

**Issue by rodrigoapereira** [locaweb/heartcheck-webservice#26]
**Motivation**
----
We need to know the test coverage for this project.

**DoD**
----
* Add simplecov as development dependency
* Add simplecov-gem-adapter as development dependency
* Configure the simplecov to run

**Comment by ewelinasobora** [comment]
@rodrigoapereira Hi, I opened a PR for this issue, let me know if it looks ok, please. Thanks!

**Comment by rodrigoapereira** [comment]
@ewelinasobora Thanks your PR is reviewed and approved!
